### PR TITLE
Many changes:

### PR DESCRIPTION
**Pull request by bjitivo**
- Made the Classes command return a paged request that fetches a subset of
  all classes; necessary to allow IntelliJ to read the whole list of classes
  when there are many classes by fetching them page by page
- Added an AllClasses command to get all classes in one go, which is equivalent
  to the old Classes command, and updated the command line controller to use
  AllClasses
- Changed the response message for FilesFullPath to be a Files value instead of
  the previously-added FilesFullPath message, since the FilesFullPath message was
  identical in nature to the already existing and now re-used Files message
- Changed CurrentThread message to ThreadLocation to be more explicit and added
  some additional data to it to allow IntelliJ Haxe plugin to have all of the
  data it needs to show thread status
- Support a new GetStructured request with a Structured response that gets a
  structured version of the value instead of a textual version, that allows for
  IDE style data displays
- Fixed parsing of class:function breakpoints in command line controller
- Allow file:line breakpoints to be handled separately and to work properly
  in command line controller
- Fixed command line controller parsing of some commands
- Fixed documentation of filespath command
- Allow up to 2 MB messages to support big projects
- Fix a deadlock bug when setting current thread
- Simplified the return types of some Commands to OK where no useful data was
  being returned in the previously more specific responses
- Add some more detail to error messages
- Fix some reflection logic to fix some data evaluation bugs
- Bumped debugger protocol version to 1.1 to reflect changes
- Allow HaxeServer class to specify the IP address to listen on as well as the
  port, to ensure that remote processes can attach to the debugger

### CODE REVIEW

**Comment by bjitivo** [comment]
Heads up: I'll merge this request on 2015.07.15 if I don't hear anything sooner.

**Comment by Simn** [comment]
Hey that's one month early!

Just kidding. ;) Thanks for your work on this!

**Comment by bjitivo** [comment]
Whoops, sorry, meant to say 2015.06.015 in my comment from 3 days ago.  Well anyway, this just brings in all of the outstanding changes that we had in the TiVo/debugger repository.  We've been sitting on some fixes and other outstanding changes necessary to make the debugger work in IntelliJ for some time now and it's good to have them in the official repo now.

Question: how do we go about publishing this version to lib.haxe.org?  I think only "gamehaxe" has rights to push the haxelib ...

**Comment by Simn** [comment]
gamehaxe is @hughsando

**Comment by hughsando** [comment]
If you add your name (your haxelib login name, that is) to the "contributors" section in the haxelib.json file and push the change, I can then do a release for you.  Once this is done, you will be able to do releases too.

I have a build-server that bundles the repo into a .zip file in haxelib format, and you should be able to get the latest from http://nmehost.com/hxcpp-debugger/
The last digit in the build-number is automatic if you use this method.
If you prefer, once I make a submit with your contributor name, you can control the release however you like.

**Pull request merged**
